### ISSUE TITLE
eject (feature request)

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#10]
Were you planning on re-adding the eject disk hotkey function from 3RXV2? It was actually rather useful.

**Comment by malensek** [comment]
I almost have this done. The new version will eject both CDs/DVDs/etc and USB disks, I just need to do a little more testing and I'll get it posted.

**Comment by greatwroth** [comment]
Sounds great, take your time.

**Comment by malensek** [comment]
B5 implements eject functionality:

http://matthew.malensek.net/projects/3RVX/3RVX3-B5.zip

The hotkey UI needs a little improvement (showing the drive letter in the list) but it seems to be working on my setup.

**Comment by greatwroth** [comment]
Works with disk drive, haven't had time to do much testing on anything else.
