### ISSUE TITLE
Hotkey Win + + fails

### ISSUE THREAD

**Issue by kascana** [malensek/3RVX#12]
The hotkey Win + + which I use for Increase Volume does not work in the new beta versions (Win + Oemplus in version 2.5). Win + - for Decrease Volume works fine.

**Comment by malensek** [comment]
Interesting, what version of Windows are you running? I'll see if I can reproduce this today.

**Comment by kascana** [comment]
Win 7. Any other combination works, only Win + + doesn't.

**Comment by malensek** [comment]
Does it just start the magnifier program instead? Some Windows hotkeys can be overridden and some can't... I'll probably need to add some extra logic to work around this bug.

**Comment by kascana** [comment]
It doesn't because I've discarded the magnifier. The issue with Win + + affects only the beta versions; in the older version 2.5 the same hotkey does work perfectly on the same machine. I tested the last beta version with Shift + Win + + which also works. So it is only Win + + (hotkey combination="524475" in the Settings.xml) which for some strange reason does not react at all.

**Comment by malensek** [comment]
Ok, it seems like even after removing the magnifier the Shell process still registers that hotkey. I have added some logic to work around this, hopefully I can get a new beta posted soon for you to test.

**Comment by kascana** [comment]
If the Shell process still registers that hotkey, this could be the case only when using the beta versions, for the same hotkey does work flawlessly in v2.5. Anyway, I am very glad that you have found a solution. Thanks for your efforts!

**Comment by kascana** [comment]
Just to confirm that after the release of beta 6 I don't have the issue anymore. Great job!

**Comment by malensek** [comment]
Good to hear --- the reason you were seeing different behavior between the two versions was a difference in how the hotkeys were implemented. Now if the new hotkey registration fails, it falls back on the behavior in v2. Thanks a lot for testing!
