### ISSUE TITLE
Weird startup

### ISSUE THREAD

**Issue by bilogic** [malensek/3RVX#125]
![image](https://github.com/malensek/3RVX/assets/946010/f54c3a00-05d9-4207-b0ef-64e3e534c86e)
![image](https://github.com/malensek/3RVX/assets/946010/c34f09b9-bd88-4b74-8934-aadbaafe4cdd)

I run a batch file at boot, which in turn starts 3RVX as Administrator. But it starts up strangely, see screenshots.
If I open a DOS prompt and run the same commands `start 3RVX.exe`, it runs properly.

Any idea what might be the issue?

**Comment by deton24** [comment]
Both, batch file, and 3RVX is set to be opened as admin?

**Comment by bilogic** [comment]
Hey thanks for getting back. I eventually found the issue. I had 2 copies on my disk, startup ran A while CLI ran B. My bad.
