### ISSUE TITLE
volume level issue when changing devices

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#15]
Whenever I use my TV which is set to full volume in software and then switch back to my internal speakers and change the volume it jumps to full volume.

**Comment by malensek** [comment]
Ah yeah, thanks for catching this. I'll get a fix posted soon, just need to do a little more testing.

**Comment by malensek** [comment]
Give this exe a try, it should fix the bug:

http://matthew.malensek.net/projects/3RVX/3RVX3-B7-pre1.zip

Hopefully your ears/speakers didn't get blown out thanks to this issue....

**Comment by greatwroth** [comment]
XD did startle me a bit the first time, but as far as I have tested this fixes it, thank you
