### ISSUE TITLE
Compatibility with older skins

### ISSUE THREAD

**Issue by kongming819** [malensek/3RVX#16]
I'd like to be able to use older skins from version 2.5 in the new version. Is there a quick and easy way to do this? I tried to rewrite the skin XML for Ice but the Settings UI still crashes every time I try to select it.

That said, is crashing when selecting a 2.5 skin a bug/unintended consequence?

Thanks!

**Comment by malensek** [comment]
Older skin compatibility is on my to-do list, but the crash definitely shouldn't happen. I'll get that fixed in the next version. Thanks!

**Comment by kongming819** [comment]
Cool! Just to be clear, though, the crash happens only on the Settings UI, not with the main program itself. Thus, 3RVX continues to run (which is great), but ya know...

Is there a better way of rewriting the XML? I used the newer skins' XML as a basis for rewriting, but that didn't seem to work.

**Comment by malensek** [comment]
Since this was added in the latest beta, I'll close the issue for now -- if anyone has problems with v2 compatibility, feel free to open new issues!
