### ISSUE TITLE
From Volume = 0% to first division up always adds division size -1

### ISSUE THREAD

**Issue by stupoole** [malensek/3RVX#17]
Pressing volume up increases the volume %age by 2 in my skin normally. I changed it to be 10 and 20 to test. It doesn't matter what size the division is, when I change from 0 up, it adds the division size minus one.

e.g. with size of 2, first increase takes it to 1% and if it's 20, it adds 19%.

**Comment by Walkman100** [comment]
Is it only when increasing from 0, or after that as well?

**Comment by stupoole** [comment]
Only when increasing from 0.

**Comment by malensek** [comment]
Hey Stu,

Would you mind posting your skin's xml? Does this happen with any of the other skins?

Thanks!

**Comment by stupoole** [comment]
It doesn't appear to happen with anything else. I am only trying to go up 2% at a time, however. 
The xml:
> http://pastebin.com/Gj7R19S6

**Comment by stupoole** [comment]
So, by changing skin and changing back, the issue appears to be fixed. If I find that it returns I will create a new issue. 

I managed to add the %age as well so thank you, Matthew.

**Comment by malensek** [comment]
Great, thanks for testing this out, and definitely let me know if it comes back.
