### ISSUE TITLE
Will "Custom Volum Change Amount" come soon?

### ISSUE THREAD

**Issue by AngryLifeender** [malensek/3RVX#18]
That's the only feature I need and I'm satisfied with this program after that :+1:
![ss 2015-05-13 at 06 12 36](https://cloud.githubusercontent.com/assets/12432138/7615205/525a7552-f99c-11e4-9e14-efce10c65518.png)

**Comment by malensek** [comment]
Yep, I should have this ready to go this weekend. It will support a custom percentage and custom number of volume "units" as well -- I will try to release a new beta in the next couple days. Thanks!

**Comment by AngryLifeender** [comment]
Awesome man, you're the best!

**Comment by AngryLifeender** [comment]
Well, Windows 8 and my Anti-Virus is doing everything they can to block Beta 7.
While Beta 6 work flawlessly for me, I just need this feature and it would be perfect. However, Beta 7 is having a lot of problems, I think it's because of my anti-virus, but I'm not sure. Anyways, I sadly didn't see "Custom volume change amount" or any options like that in beta 7 as you promised :/

**Comment by malensek** [comment]
Hmm, what kind of problems are you running into (also, what anti-virus is it?)

For the custom volume change amounts, I should've made it more obvious, but it got moved to the hotkey setup tab. So when you create an "Increase volume" hotkey, you should now be able to select a custom amount (in either skin "units" or as a percentage)

Thanks a lot for testing this out!

**Comment by AngryLifeender** [comment]
Oh sorry, I should have noticed that it was there lol.
I deleted and re-downloaded Beta 7. Than I allowed Windows 8 and my Anti-Virus to run 3rvx.exe and settings.exe. And now it seems to work awesome I think! Thank you!

**Comment by AngryLifeender** [comment]
The Anti-Virus is "Norton Internet Security Online". The first time I clicked the hotkey I had for Volume up or down, Norton blocked settings.exe. The name of the threat is "Sonar.Heuristic.120", what ever that means. After I allowed that to run, this program started working great. Hope this helps in any way.
![ss 2015-05-22 at 02 08 11](https://cloud.githubusercontent.com/assets/12432138/7761922/9df2b77c-002c-11e5-98ff-b404cc1ad998.jpg)
Info of this threat by Norton:
http://www.symantec.com/security_response/writeup.jsp?docid=2014-011016-0119-99&vid=4294921081&prod=scss&product=Norton%20Internet%20Security%20Online&version=21.7.0.11&plang=sym:NO&layouttype=SOS&buildname=SymantecPartner&heartbeatID=D27D6B50-9FAA-4B49-B023-8408BDA2820D&env=prod&ispid=1004&sitename=NO&vendorid=Symantec&plid=0&skup=21322692&skum=21322692&skuf=21291108&endpointid=%7BD27D6B50-9FAA-4B49-B023-8408BDA2820D%7D&partnerid=Symantec&lic_type=64&lic_attr=152594&osvers=6.3&oslocale=iso:NOR&oslang=iso:NOB&os=windows

**Comment by jackwilsdon** [comment]
> Heuristics is a feature which uses a lot of artificial intelligence techniques for detecting malware in the system, rather than depending on signatures.
> This advanced feature can cause a lot trouble in the developer environment by reporting false positives. > This false positive may be also because of the programming style or libraries used.
>
> [Source](http://community.norton.com/en/comment/5336613#comment-5336613)

So it looks like there isn't much that can be done apart from [submitting the beta as a false positive](https://submit.symantec.com/false_positive/)

**Comment by AngryLifeender** [comment]
If you were asking me, it doesn't seem like it is making any network requests, nothing I know of atleast. But I submitted settings.exe as a false positive and I got a mail from Norton saying that they fixed it. So the same should not happen to anyone in the future for Norton users using Beta 7 I think.

**Comment by malensek** [comment]
Thanks for letting them know about this. It'll be interesting to see if it keeps getting flagged in the future.. As far as network requests go, neither program does anything like that, but that does remind me that I should probably implement an "auto update" feature at some point.... :-)

**Comment by malensek** [comment]
I'll close this for now since the feature is there, but if further Norton-related problems crop up later feel free to open a new issue.
