### ISSUE TITLE
"run on windows startup" not working in B7

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#19]
checking "run on windows startup" creates an entry targeting "C:\Program Files (x"

**Comment by techNeffect** [comment]
Can confirm. I simply edited the registry entry to have the full path, but yeah, is an issue.

**Comment by jackwilsdon** [comment]
Pretty sure it was fixed by aeb073719a6ef6eca5b730926986df0406b4c33a, although I don't know which build that commit has been included in.

**Comment by malensek** [comment]
Yeah, this should be fixed now, and I'll post a new build really soon (work has been a bit crazy for me lately, so things are taking a bit longer than usual).

**Comment by malensek** [comment]
Based on my tests on a couple computers, this seems to be fixed in the latest beta... I'll close this issue for now. :-)
