### ISSUE TITLE
changing audio device

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#2]
I use 2 audio devices that require system volume control; the internal speakers and a wireless headset. When switching between these 3RVX is still attached to the previous device until I bring up the settings window and click save. The major annoyance is that when switching from my headset to my internal speakers (via unplugging the headset) then attempting to change the volume without going through the settings window fix 3RVX will crash. Can you make 3RVX detect and switch to new active audio devices?

**Comment by greatwroth** [comment]
Any news? I saw the "Beta 1" build on your site, is it recent? Does it have this feature without being a debug version?

Oh, i seems the Beta 1 link doesn't actually go anywhere (404).

**Comment by malensek** [comment]
Alright, sorry for the long delays, I was away for a while and had to get caught up.

The beta posted now should handle the device changing at runtime. It also lets the user select the desired default audio device from the tray icon, but I haven't put a combo box in the settings to make the change permanent quite yet.

This is the total rewrite from the ground up, so some features are missing, but at this point the base is solid and functionality will be implemented faster.

**Comment by greatwroth** [comment]
will do some thorough testing once I can get my skin ported over, so much has changed that my old skin actually crashes the program

**Comment by greatwroth** [comment]
I think with the new beta we can declare this resolved. Thank you for all the work you put into this.
