### ISSUE TITLE
Not sound effects for every volume key press when using a change amount percent less than the Volume Unit

### ISSUE THREAD

**Issue by AngryLifeender** [malensek/3RVX#20]
For example, if I use 1 percent change amount, I can only hear the sound effect every 6th percent I go up in volume, because the "Classic" skin has around 6 percent volume in each "volume unit". 
When you're using a Change Amount Percent less than the unit, there should be an option to choose that you want sound effects for every volume key press. Thanks

**Comment by malensek** [comment]
Oh yeah, this is a really good point. I will get an option put in for this, and it should probably be the default behavior.

**Comment by AngryLifeender** [comment]
Awesome man. I think it should too.

**Comment by malensek** [comment]
This change is now in B8, let me know what you think.
