### ISSUE TITLE
beta issues

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#3]
Just a list of issues I have come across to be hammered out as you see fit. Will add as I find more and apologies for any you are already aware of.

- (more feature request than bug) could not figure out if/how glass for background can be used
- ~~restart required after skin change for OSD to change~~ *fixed*
- ~~volume control hotkeys cannot be changed (if you change them they will not work, only the original combos work if they are set) **this is the only real issue preventing daily use for me**~~ *fixed*
- ~~volume notification icon can not be disabled~~ *fixed*
- ~~multiple instances of the settings window can be opened (essentially another feature request as this isn't really an issue)~~ *fixed*
- ~~OSD displays whenever starting a sound stream~~ *fixed*

**Comment by malensek** [comment]
Glass is temporarily disabled because I'm developing this on Windows 8 (and it doesn't support glass as far as I know). I do have this implemented though so it shouldn't be too hard to test and get enabled.

The hotkey thing is strange. Is it changing the settings file properly...? If you restart the settings app, does what you configured show up?

The rest should be quick fixes.

**Comment by greatwroth** [comment]
The settings file changes and persists in the settings window but the combos just don't work. This is only a problem with vol+, vol-, and mute.

**Comment by malensek** [comment]
Alright, I think I have all these just about fixed apart from the hotkey issue. Would you mind sending the <hotkey> tags from your settings.xml?

Thanks for all your help!

**Comment by jackwilsdon** [comment]
I can confirm I'm experiencing the same issue with the hotkeys. I have bound volume up/down to CTRL+ALT+UP/DOWN and mute to CTRL+ALT+LEFT. [Here is my Settings.xml](https://gist.github.com/jackwilsdon/7d1b98f690b30806b4d3).

**Comment by greatwroth** [comment]
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<settings>
    <skin>wrothskin</skin>
    <language>English</language>
    <audioDeviceID/>
    <notifyIcon>false</notifyIcon>
    <soundEffects>false</soundEffects>
    <onTop>true</onTop>
    <hideFullscreen>true</hideFullscreen>
    <hideAnimation>fade</hideAnimation>
    <hideDelay>800</hideDelay>
    <hideSpeed>765</hideSpeed>
    <osdPosition>bottom</osdPosition>
    <osdEdgeOffset>140</osdEdgeOffset>
    <osdX>0</osdX>
    <osdY>0</osdY>
    <hotkeys>
        <hotkey combination="524479" action="6"/>
        <hotkey combination="655655" action="0"/>
        <hotkey combination="655653" action="1"/>
        <hotkey combination="655656" action="3"/>
    </hotkeys>
    <monitor></monitor>
</settings>
```

win + / = open settings 
win + ctrl + left = volume down 
win + ctrl + right = volume up 
win + ctrl + down = mute

**Comment by malensek** [comment]
Okay, give this version a try: (it has everything, except for glass. I need to get a Windows 7 VM set up so I can test)

http://matthew.malensek.net/projects/3RVX/3RVX3-B2.zip

**Comment by jackwilsdon** [comment]
That's it! Works perfectly.

**Comment by greatwroth** [comment]
I can confirm that all issues (except glass of course) are fixed, very nice work, thank you.

Also if you don't already have a VM preference I suggest VirtualBox.

**Comment by greatwroth** [comment]
I've also noticed that whenever an audio stream starts (notification sound, music, video with sound) the OSD pops up. Best way to see my point is to test a windows notification sound repeatedly.

**Comment by jackwilsdon** [comment]
@greatwroth, how are you testing the Windows notification sound? Clicking the volume slider to make the sound will show the OSD, as Windows emits a volume change event (even if the volume doesn't actually change).

**Comment by greatwroth** [comment]
I right click the taskbar volume icon, click sounds and then test the "asterisk" sound.

**Comment by jackwilsdon** [comment]
Interesting, looking at the [source](https://github.com/malensek/3RVX/blob/master/3RVX/OSD/VolumeOSD.cpp#L237), it seems that the OSD is only shown due to Windows events when the event is a `MSG_VOL_CHNG` (volume change) or `MSG_VOL_DEVCHNG` (audio device change), although I might be reading the source wrong.

**Comment by greatwroth** [comment]
I do use Realtek HD Audio Manager, but there isn't much to it and the problem persists even without it. Have you actually tested this with the newest beta yourself and gotten different results?

**Comment by malensek** [comment]
For the hotkey thing, I was corrupting any of the "extended keys" which happen to include a lot of the keys on the keyboard. Thanks to both of you for testing!

I just got a virtualbox setup with Windows 7 so I will hopefully get the glass thing done tonight.

As for this issue with the OSD popping up, that's a weird one. I'm not seeing the same behavior here, but there are a few reasons this could happen. @greatwroth, would you mind running that old console-based test program I posted and see what it prints after you play the test sound?

**Comment by jackwilsdon** [comment]
@greatwroth I'm currently using the [B2 Build](http://matthew.malensek.net/projects/3RVX/3RVX3-B2.zip) as posted higher up in this issue. Not getting any popups except for when changing volume/sound card using Realtek HD Audio Manager.

**Comment by greatwroth** [comment]
Started debug program, tested sound, closed program.
```
  _____ ______     ____  _______
 |___ /|  _ \ \   / /\ \/ /___ /
   |_ \| |_) \ \ / /  \  /  |_ \
  ___) |  _ < \ V /   /  \ ___) |
 |____/|_| \_\ \_/   /_/\_\____/

Starting up...
[Init:78]
Initializing...
[CoreAudio::AttachDefaultDevice:36]
Attached to audio device: [TV (NVIDIA High Definition Audio)]
[Settings::Settings:13]
Loading settings file [Settings.xml]
[Skin::Skin:18]
Loading skin [TestSkin]: Skins\TestSkin\skin.xml
[Meter::Meter:23]
Loading meter bitmap: Skins\TestSkin\OSD\meter.png
Status: 0
[Skin::LoadMeter:120]
Created meter [horizontalendcap]:
Geometry: (71, 29); 0x14
Units: 28
Current Value: 0 (0 units)
[Skin::LoadMeter:120]
Created meter [text]:
Geometry: (362, 29); 45x23
Units: 100
Current Value: 0 (0 units)
[Meter::Meter:23]
Loading meter bitmap: Skins\TestSkin\OSD\bitstrip.png
Status: 0
[Skin::LoadMeter:120]
Created meter [bitstrip]:
Geometry: (37, 30); 21x14
Units: 4
Current Value: 0 (0 units)
[Skin::LoadMeter:70]
Could not find meter bitmap: Skins\TestSkin\OSD/tile.png
[Skin::LoadMeter:70]
Could not find meter bitmap: Skins\TestSkin\OSD/tile.png
[MeterWnd::Update:5]
Updating meter window
[MeterWnd::Update:18]
Contents have changed; redrawing
[MeterWnd::Update:29]
Drawing meter:
Geometry: (71, 29); 0x14
Units: 28
Current Value: 0 (0 units)
[MeterWnd::Update:29]
Drawing meter:
Geometry: (362, 29); 45x23
Units: 100
Current Value: 0 (0 units)
[MeterWnd::Update:29]
Drawing meter:
Geometry: (37, 30); 21x14
Units: 4
Current Value: 0 (0 units)
[MeterWnd::Update:5]
Updating meter window
[MeterWnd::Update:18]
Contents have changed; redrawing
[MeterWnd::Update:29]
Drawing meter:
Geometry: (71, 29); 303x14
Units: 28
Current Value: 1 (28 units)
[MeterWnd::Update:29]
Drawing meter:
Geometry: (362, 29); 45x23
Units: 100
Current Value: 1 (100 units)
[MeterWnd::Update:29]
Drawing meter:
Geometry: (37, 30); 21x14
Units: 4
Current Value: 1 (4 units)
[Settings::Hotkeys:36]
Adding hotkey mapping: 524296 -> 100
[HotkeyManager::Register:66]
Registered new keyboard-based hotkey: 524296
[VolumeOSD::WndProc:74]
Display duration has elapsed. Hiding window.
[VolumeOSD::AnimateOut:46]
Finished hiding window.
Volume level: 100
[MeterWnd::Update:5]
Updating meter window
[VolumeOSD::WndProc:74]
Display duration has elapsed. Hiding window.
[VolumeOSD::AnimateOut:46]
Finished hiding window.
```
AH, here's something new I just figured out while testing, I've been using my HDTV connected via HDMI all day, this issue only seems to occur with that setup.

**Comment by malensek** [comment]
And so in this case, the default audio device is the TV (HDMI)?

I think I have a similar setup. I'll test and see what happens.

**Comment by greatwroth** [comment]
Yes,  I have it set up so that whenever I plug in the HDMI cable plugged into my TV it automatically sets it as the default audio device.

**Comment by Walkman100** [comment]
Doesn't the HDMI audio out use a different driver? I know my onboard audio uses the Realtek driver, but my onboard HDMI audio out uses the Intel HDMI audio driver, and my graphics card HDMI uses the AMD HDMI audio driver.

**Comment by greatwroth** [comment]
That is correct.

**Comment by malensek** [comment]
Well, it turned out my TV setup didn't do this after all. I might be taking a stab in the dark, but check and see if this version helps:

http://matthew.malensek.net/projects/3RVX/3RVX3-B3.zip

If not, I've included a debug version that prints some extra info that should probably help determine what's going on.

**Comment by greatwroth** [comment]
That actually seems to have fixed it, what did you change?

**Comment by malensek** [comment]
Now it checks to see whether the volume actually changed when it receives a notification. At some point I'd like to see if there's any other way of distinguishing this, but I think doing this check is a good idea anyway...

**Comment by jackwilsdon** [comment]
Looks like all of the issues are resolved for now then, nice work.

**Comment by malensek** [comment]
I finally got a version with glass support finished (Beta 4). I have included a skin that uses glass 'Vista 808.'

http://matthew.malensek.net/projects/3RVX/3RVX3-B4.zip

**Comment by greatwroth** [comment]
Glass works perfectly, my skin is finally back the way I used to have it. I did have one more thing that got lost among the more important issues but I will create a new issue for it so we can close this one. Again, I am so glad you started working on 3RVX again, thank you.
