### ISSUE TITLE
 installed beta8 ( + win10 ) -> no settings save

### ISSUE THREAD

**Issue by tg44** [malensek/3RVX#30]
When i start the application (admin or not admin privs both broken), the settings menu doesn't save for the apply button.
If you make a settings file (like in the zip), and give the settings.exe admin rights to run, its do the job.
Othervise its greatly works on win10 too I think its just a small packing problem.

**Comment by malensek** [comment]
I'll get Windows 10 installed so I can check it out... Thanks for letting me know!

**Comment by malensek** [comment]
Hey tg44, if you navigate to %APPDATA% in the file explorer, has a 3RVX entry been created? (should be a folder named "3RVX" with Settings.xml inside). I just upgraded to Windows 10 and I'm not seeing this bug, but it might've been because of the upgrade...

When you hit 'Apply' in the settings app, does the program reload (show the volume OSD?)

**Comment by tg44** [comment]
There is an xml with language settings, and if I rename the xml in the pf its now write the xml in the app data when I hit apply.
Possible other problems: my username in this computer contains 'ö'

And I tought its fixed itself but the problem is not the writeing. Its not loading back. When I hit apply the xml get a new timestamp every time. If I close the window and open it again it didn't preload the beforely checked options, and when I hit apply again its save a nearly empty (but proper) settings file. 

The Clog doesn't write to the cmd output :( How coud I force to see the clog outputs?

I checked the source I have no idea why it can write but couldn't read. I give myself an hour to check this :)

**Comment by tg44** [comment]
The problem is definitely the "ö" in the user name. See the pull req and the link in it. I think it will fix the problem and will not generate new ones :)

**Comment by malensek** [comment]
Hey Gergő,

Thank you so much for tracking this down and figuring out what was going on. Reading the XML files should not have been using those StringUtils functions anyway, so I updated the code to open and read the files properly now (sometimes unicode is hard, I guess :-))

Would you mind pulling in the changes I made and testing it out (I will as well, shortly)? We need to keep the UTF-8 code page in Narrow() for reading XML data (which is actually formatted as UTF-8, unlike the string I was passing to it earlier)

**Comment by tg44** [comment]
It's working here.

**Comment by malensek** [comment]
Awesome, thank you!
