### ISSUE TITLE
Logarithmic volume increments?

### ISSUE THREAD

**Issue by gcormier** [malensek/3RVX#32]
Just throwing it out there.. for those of us with external speakers set to near-max.. the first few increases have a more drastic change if you're casually working or listening to music, then if you're partying and you want to go from loud to louder :)

Would logarithmic increments be something supported? I guess it would require 3rvx to know what the current volume is.. then it can increase it by smaller amounts if it's low, and get increasingly larger increments as the volume is jacked.

Stackoverflow has some algorithms for implementing it :

http://stackoverflow.com/questions/1165026/what-algorithms-could-i-use-for-audio-volume-level

**Comment by malensek** [comment]
Hmm, that's a great idea, and probably should've been an option from the start. I'll do some experimenting and hopefully I can get this put into the next beta!

**Comment by Danita** [comment]
:+1: I was about to suggest the same!

**Comment by malensek** [comment]
I've just about got something ready for this, where the curve can be configured as well to make it more or less sensitive. Hopefully will have an update ready in the next few days!

**Comment by gcormier** [comment]
Is there a build ready for testing?

**Comment by malensek** [comment]
I'll try to get something put together in the next couple days!

**Comment by malensek** [comment]
(I see that's what I said before -- but now I REALLY mean it... ;-))

**Comment by malensek** [comment]
Ok, I haven't finished reworking the settings app to support this yet (I'm in the process of adding an OSD settings tab where this will be), but I thought I'd push out a prerelease for testing the volume curve modification: http://3rvx.com/releases/3RVX-2.9.2-pre2.zip

If you replace the executables in your current install with these, you will also need to replace the "Classic" skin (it has been updated with Brightness images).

To activate the curve adjustment, you'll need to modify your Settings.xml (%APPDATA%\3RVX\Settings.xml if you're using an installer version) and add a curveAdjust tag like:

    <curveAdjust>3</curveAdjust>

The number provided to curveAdjust represents the "strength" of the curve modification. Here's what the curves look like on my system (I believe these could vary based on hardware (?)):

![curve](https://cloud.githubusercontent.com/assets/2635718/10676891/56ca5a22-78c6-11e5-83e7-1cc553029670.png)

Where 0 is the original unmodified curve, 4 gives a roughly linear increase in output dB. Beyond that, things start to get a little extreme on the loud end. In the next few days I'll also finish adding support for a volume limiter, which would put an upper bound on the high end of the curve (while still applying the desired curve adjustment)

For the UI of the settings app, I was planning on adding a simple dropdown for this with some predefined values (maybe 1 through 10). Let me know if you think there's a better way to adjust this/convey it to the user.

**Comment by gcormier** [comment]
Oh man, it's heaven! It works really well at high volumes! It does scale
quickly at the high end, but 99% of the time I am listening at the low end.

Can you use either % or volume units and they are both affected by the
curve?

For the configuration, what about :

[checkbox] Enable Logarithmic Volume
[dropdown] Log strength (or correction?)
Low
Medium
High
Custom

Greg

**Comment by malensek** [comment]
That sounds good to me. I'm working on getting the UI updated for this... What levels do you think should correspond to low, medium, and high?

For the % and units, both are affected. It would be possible to add an option to override it in the hotkey setup, though...

**Comment by svnpenn** [comment]
@malensek these are my results with test version:

~~~
0 | 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52
  | 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100
--+-----------------------------------------------------------------------------
1 | 0 3 6 8 11 14 16 19 21 24 26 29 31 33 36 38 40 42 44 46 49 51 53 55 57 58 60
  | 62 64 66 68 70 71 73 75 77 78 80 82 83 85 86 88 90 91 93 94 96 97 99 100
--+-----------------------------------------------------------------------------
2 | 0 4 8 12 16 19 22 25 28 31 34 37 39 42 44 46 49 51 53 55 57 59 61 63 64 66
  | 68 69 71 73 74 76 77 79 80 82 83 84 86 87 88 90 91 92 93 94 96 97 98 99 100
--+-----------------------------------------------------------------------------
3 | 0 6 12 17 21 26 29 33 36 39 42 45 47 50 52 54 57 59 61 62 64 66 68 69 71 72
  | 74 75 77 78 79 81 82 83 84 85 86 88 89 90 91 92 93 94 95 96 97 98 99 100
--+-----------------------------------------------------------------------------
4 | 0 9 17 23 28 33 37 41 44 47 50 53 55 57 59 61 63 65 67 69 70 72 73 75 76 77
  | 78 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100
--+-----------------------------------------------------------------------------
5 | 0 14 23 30 36 41 45 48 52 54 57 59 62 64 66 67 69 71 72 74 75 76 77 79 80 81
  | 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100
--+-----------------------------------------------------------------------------
6 | 0 20 30 38 43 48 52 55 58 60 63 65 67 69 70 72 73 75 76 77 79 80 81 82 83 84
  | 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100
--+-----------------------------------------------------------------------------
7 | 0 26 37 44 50 54 57 60 63 65 67 69 71 73 74 76 77 78 79 80 81 82 83 84 85 86
  | 87 88 89 90 91 92 93 94 95 96 97 98 99 100
--+-----------------------------------------------------------------------------
8 | 0 33 44 50 55 59 62 65 67 69 71 73 74 76 77 78 80 81 82 83 84 85 86 87 88 89
  | 90 91 92 93 94 95 96 97 98 99 100
~~~

This appears to give less control on the lower range, which is the exact
opposite of what I want. I want smaller increments on the soft range and larger
increments on the loud range.

**Comment by malensek** [comment]
That doesn't seem to be acting right. Are these values reported by the windows mixer? Also, what skin/hotkey/etc are you using so I can try to reproduce this behavior? Thanks!

**Comment by svnpenn** [comment]
> Are these values reported by the windows mixer?

Yes

> Also, what skin/hotkey/etc are you using

Vista Glass / <kbd>Volume +</kbd>

**Comment by svnpenn** [comment]
@malensek any comment?

**Comment by malensek** [comment]
Hey Steven, I think I have this solved, but it will take fixing another bug to fully fix the problem. Sorry for the long wait! I've been traveling, so don't always have a great internet connection. I need to go through a few commits that should have this working as expected. Thanks!
