### ISSUE TITLE
Issue with multi-monitor OSD when starting program with 2nd monitor disabled

### ISSUE THREAD

**Issue by havenwind** [malensek/3RVX#36]
Hi, I encountered a small issue with multi-monitor OSD while using the "Display Device: All Monitors" option. I'm using the newest Beta 9.

If I start the program while all my monitors are enabled, the volume OSD is displayed correctly on all monitors. But if I start the program while only one monitor is active, and then enabling a 2nd monitor, the OSD is not displayed on the 2nd monitor. I'd need to restart the program for the OSD to be displayed on all monitors. 

I did a couple of testing, and I found if I start the program when all monitors are enabled, then disabling the 2nd monitor, and then re-enabling the 2nd monitor, the OSD is displayed correctly on all monitors. I'd love the OSD to be displayed on all monitors regardless of the order the monitor is enabled. Is this a limitation with how Windows handles multi-monitors?

It's just a small issue, not that much of a problem. Please take a look at it if you have the time.

**Comment by malensek** [comment]
Thanks for reminding me -- I think I have a TODO stuck somewhere in the code describing exactly this situation. It shouldn't be too much trouble to get fixed, I'll take a look!

**Comment by havenwind** [comment]
Cool, looking forward for the update!

**Comment by malensek** [comment]
Hey havenwind, sorry for taking forever to get you an update on this! Would you mind trying out this pre-release?

http://3rvx.com/releases/3RVX-2.9.2-pre1.zip

Extract the exe from that zip, copy over your existing 3RVX exe, and let me know if this solves the problem -- it seemed to on my setup.

Thanks!!

**Comment by havenwind** [comment]
Sweet, I've tested it and it works just like expected! Thanks a lot!!
