### ISSUE TITLE
3RVX 2.5 "eats" more and more memory?

### ISSUE THREAD

**Issue by AX-Turbo** [malensek/3RVX#40]
Hello,

(sorry, I´m from Germany > rookie english) I´m using 3RVX 2.5 and noticed shortly that, if 3RVX task idles, it reserves more and more system memory. This happens uninterrupted if I´m typing text or if I move the mouse! As soon as a press a typical "3RVX key" (mute, louder etc.), memory usage drops down to ~2MB. After that, same memory fill-up issue begins again. Screenshots after ~30 minutes as attachment.

Can anyone else observe this? Apart from that, thank you for this nice little tool. :)

![3rvx](https://cloud.githubusercontent.com/assets/16238956/11714018/55587132-9f37-11e5-80a7-8eeb36f5337a.jpg)

**Comment by malensek** [comment]
Hey AX-Turbo,

3RVX 2.5 was built using C# and the .NET framework, so the app is running in a memory-managed environment that periodically "garbage collects," which is what you're seeing here. There are some workarounds for this, but generally memory consumption will fluctuate in these .NET apps.

The new version of 3RVX (v3) is written in unmanaged C++, so it uses much less memory and shouldn't fluctuate over time like the old version. If you're willing, give the latest beta a try (Beta 9) -- there may be a few bugs but things are getting more stable, and some of the old 2.5 bugs are actually fixed as well.

And your English is very good!

Thanks!
Matthew

**Comment by AX-Turbo** [comment]
Ok downloaded V3 Beta 9, runs fine and with constantly low memory usage here. Cool. :+1: 

A litte hint for V3 Beta 9, if it wasn´t already reported - after restart, the deselected option "Enable volume notification icon" is always activated again. Had to deactivate it manually at settings.xml <notifyIcon>false</notifyIcon>. But that is only a peanut, still a essential little tool for me. Thanxx and keep it up!
