### ISSUE TITLE
Reset window position when changing resolution/monitor

### ISSUE THREAD

**Issue by Nvidiot** [malensek/3RVX#44]
3RVX has a great default position on the screen, however when I change screen resolution or plug in a second (different resolution) monitor, the position is not recalculated. I can work around it by closing the application and re-opening it, but this is rather inconvenient.

**Comment by malensek** [comment]
Is this on v2.5 or the new betas? This *should* be fixed in the latest betas.

**Comment by Nvidiot** [comment]
It was on the 2.5 version, the new beta fixes it, awesome!
