### ISSUE TITLE
Feature Request - set mute if display is locked

### ISSUE THREAD

**Issue by robinhodk** [malensek/3RVX#48]
Option that enable "mute", if computer (or display) will be locked (Win + L).
Nice to have:  log in --> disable mute and music goes on.

It's not working to set the Hotkey Win + L and the cmd mute.

**Comment by malensek** [comment]
I like that idea, and I think it would be fairly easy to implement as 3RVX already listens for lock/unlock events. I will add it to my to do list :-)

**Comment by robinhodk** [comment]
Done.
