### ISSUE TITLE
OSD not displaying on Windows 10 desktop

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#53]
I finally broke down and updated from Windows 7 to 10 on my main machine and I've found a small issue. If the focus is on the desktop the OSD will not display, if on anything else it works as expected. This was not the case in Windows 7.

**Comment by malensek** [comment]
Just a shot in the dark, if you run 3RVX as administrator does it still happen?

**Comment by greatwroth** [comment]
That's exactly what it was. I had since successfully disabled UAC (I swear they make it harder each version) and just tested now and it works. For anyone else reading, running as administrator has the same effect in this case.
