### ISSUE TITLE
Don't show Win10 volume indicator when muting/unmuting

### ISSUE THREAD

**Issue by GaryKing** [malensek/3RVX#58]
The Windows 10 system volume indicator does not appear when using volume up/down, which is good, but it still appears when hitting mute/unmute. How can I also hide the system volume indicator when hitting those keys?

Thanks in advance!

**Comment by malensek** [comment]
You should be able to create a new mute hotkey in 3RVX (just use your mute key for the key combination and mute for the hotkey action), and that will override the system OSD -- let me know if that doesn't work.

**Comment by GaryKing** [comment]
Yep that worked thanks again!

**Comment by malensek** [comment]
I really need to have those three key combos set up by default -- I'll add that to the todo list :-)

**Comment by GaryKing** [comment]
Yep, volume up, down, mute should be automatically set upon installation IMO. I've been using this app for a few days and already love it, but I've already seen a few questions asking how to enable volume up, down, mute already.
