### ISSUE TITLE
OSD doesn't show on all monitors

### ISSUE THREAD

**Issue by havenwind** [malensek/3RVX#7]
Hi, I have 3 monitors set as extended desktop. However I couldn't get the OSD to show on monitors other than the primary display, no matter what display monitor I choose in the settings. I tried \\.\DISPLAY1, \\.\DISPLAY2, \\.\DISPLAY3, All Monitors. 

Is this a known bug or is it something on my end? I'm using beta 3, really love the program by the way.

**Comment by malensek** [comment]
Hey havenwind,

Placing the OSD on a particular monitor is implemented but sounds like it's not working. I probably forgot something, let me take a look and get back to you.

As for displaying on all monitors, that functionality is about 70% done.

Thanks!

**Comment by malensek** [comment]
Ah yeah, I had forgotten I hardcoded it to the primary only. This shouldn't take too long to fix.

**Comment by havenwind** [comment]
Thanks for the quick response! Looking forward for the updated version.

**Comment by malensek** [comment]
Sorry for taking so long to get back to you, but this ended up revealing some other bugs I needed to work through. I have a new beta release ready that should respect the display you select in the settings, but I haven't finished implementing the 'all monitors' option quite yet.

http://matthew.malensek.net/projects/3RVX/3RVX3-B4.zip

**Comment by havenwind** [comment]
Thanks for the update! I can confirm that showing the OSD on display #2 works fine. 'All monitors' option would be perfect for me, just take your time!

**Comment by malensek** [comment]
Great, and I think I will have 'All monitors' finished up for B6. Thanks for testing!

**Comment by havenwind** [comment]
Hi, I can confirm that 'All montors' works for my setup. It's perfect for me now. Thanks for your hard work!
