### ISSUE TITLE
mfc120u.dll missing

### ISSUE THREAD

**Issue by gcormier** [malensek/3RVX#9]
Just did a fresh Windows 8 install, I get a missing mfc120u.dll when trying to run the settings application.

I put this on

http://www.microsoft.com/en-us/download/details.aspx?id=40784

Still no luck. Which redistributable is needed?

**Comment by malensek** [comment]
Hi gcormier,

The latest beta (B4) should include all the necessary libraries. Let me know if you're still having trouble:

http://matthew.malensek.net/projects/3RVX/3RVX3-B4.zip

**Comment by gcormier** [comment]
All good now!
